### ISSUE TITLE
Feature Idea: Entity Whitelist

### ISSUE THREAD

**Issue by TheSpicePhantom** [lukebemish/NoMorePortals#1]
A config file containing a list where people can put entities that can pass portals.
The mod would need to check if a player was riding the entity and block access to both, but the entity specified can still pass.

I'm requesting this because the mod is breaking vanilla Nether Portal Chunkloaders which is kinda bad when contraptions rely on vanilla mechanics to work.

The list should have no entites by default and block everything going through the portal.

**Comment by lukebemish** [comment]
Instead of a config, I'll implement a tag that contains entities that are allowed through the portal, which should be more flexible

**Comment by lukebemish** [comment]
The `nomoreportals:portal_allowed` tag should work, once everything gets published
